### PR TITLE
Updated regex to include textarea and more

### PR DESCRIPTION
**Pull request by bramburn**
This includes a new Regex to include texture | pre | Script within a page.

example output can be found here:

https://measuredbuildingsurvey.co/dynamic-lp/measured-building-survey/

Credit to Alan Moore and Ridgerunner

http://stackoverflow.com/questions/5312349/minifying-final-html-output-using-regular-expressions-with-codeigniter

### CODE REVIEW

**Comment by bramburn** [comment]
@GrahamCampbell I've added a test and modified the existing to match the "forced" outcome. The textarea|pre|script is left intact in the end. Except for trailing white spaces before the closing </textarea|pre|script> it still works at the end of the day.

See results on [measuredbuildingsurvey.co/dynamic-lp/measured-building-survey/](http://measuredbuildingsurvey.co/dynamic-lp/measured-building-survey/)

**Comment by GrahamCampbell** [comment]
The problem with this, is the file is not html, it's blade.

**Comment by bramburn** [comment]
Sorry I don't follow.
I'm using blade on my apps with most of the @ shortcodes .

I thought the blademinifier class parses the blade after it has converted the blade shorttags to php.
Maybe addition testing is required for other use than just HTML view.
I guess to get the Regex working properly I'll need to understand different use cases for blade.

**Comment by bramburn** [comment]
Let me know what you need me to do to get this resolved:
Whenever I have time I'll work on it

**Comment by GrahamCampbell** [comment]
My concerns are that these changes aren't safe, and my break php/blade code. We have a html minifier middleware that will minify the output in realtime, that will give best results.

The point of the blade minfy was just to give a crude minification that will reduce the size in most cases, but it was not intended to be optimal.

**Comment by bramburn** [comment]
That's fine i'll leave the changes on my branch.

**Pull request closed without merging**
