### PR TITLE
Page Speed Validation replace

### PR DESCRIPTION
**Pull request by gcphost**
Changed replace array to use the example from:
http://stackoverflow.com/a/29363569

This example does what is required to pass google page speed validation.

Sorry for another PR, trying to pass styleci.

### CODE REVIEW

**Comment by gcphost** [comment]
sorry for so many, styleci passes now

**Comment by GrahamCampbell** [comment]
These changes are not correct.

**Comment by GrahamCampbell** [comment]
You need to enable live minification for good results, using our middleware. Blade minification is only run once at compile. Your changes can totally break it.

**Comment by GrahamCampbell** [comment]
Your changes are only safe on the final output, not the input for php to run.

**Comment by GrahamCampbell** [comment]
The idea of this package is to give high performance. Don't you see that making php minify the pages at runtime every time will actually make your website slower than just having this small optimization at compile time?

**Pull request closed without merging**
