### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by SamAriafar**
1. Regex improved and also modified because there were a single space between all HTML tags
2. Inline JS and CSS compression feature added.
3. Stopped inline scripts from being skipped. However I hope to know what you have skipped them from the first place, so I can consider that either.
4. I will provide modification for the other two skipped items after some tests. In my opinion there is no need to skip the whole file from being compressed, because of some trouble-making codes.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This won't work if blade code generates the inline css/js.

**Comment by GrahamCampbell** [comment]
Use the minification middleware to minify inline content.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-HTMLMin/blob/master/src/Http/Middleware/MinifyMiddleware.php

**Comment by SamAriafar** [comment]
> This won't work if blade code generates the inline css/js.

My blade code is generating inline css/js and I have no problem using either your code (force mode) or my improved one, because both of them are working fine. I think you had better take another look. Wish I could see the blade code you get problem with, in programming world nothing is impossible to get solved.

> Use the minification middleware to minify inline content.

You know better that using that affects performance in a bad way. I prefer compression at blade compile time which is get cached after that.

**Pull request closed without merging**
